version: '3.8'

services:
  neo4j:
    image: neo4j:5.12.0-enterprise
    container_name: neo4j-rockstars-demo
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/data:/var/lib/neo4j/data
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/var/lib/neo4j/plugins
      - ./neo4j/conf:/var/lib/neo4j/conf
      - ./neo4j/logs:/var/lib/neo4j/logs
    environment:
      - NEO4J_AUTH=neo4j/neo4jneo4j
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_apoc_import_file_enabled=true
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science", "n10s"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*, algo.*, bloom.*, gds.*
      - NEO4J_dbms_security_procedures_whitelist=apoc.*, algo.*, bloom.*, gds.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*, algo.*, bloom.*, gds.*
      - NEO4J_dbms_unmanaged__extension__classes=com.neo4j.bloom.server=/browser/bloom
    networks:
      - neo4j-network
    
networks:
  neo4j-network:
